/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(massey_frame_sync_soft.h)                                  */
/* BINDTOOL_HEADER_FILE_HASH(05c26622f3de41b872571420603b9228)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/massey_frame_sync_soft.h>
// pydoc.h is automatically generated in the build directory
#include <massey_frame_sync_soft_pydoc.h>

void bind_massey_frame_sync_soft(py::module& m)
{

    using massey_frame_sync_soft    = gr::satellites::massey_frame_sync_soft;


    py::class_<massey_frame_sync_soft, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<massey_frame_sync_soft>>(m, "massey_frame_sync_soft", D(massey_frame_sync_soft))

        .def(py::init(&massey_frame_sync_soft::make),
           D(massey_frame_sync_soft,make)
        )
        



        ;




}








