/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_scrambler_soft.h)                                      */
/* BINDTOOL_HEADER_FILE_HASH(48d3bc3fc641cae79dbde5843a859cfb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <satellites/pdu_scrambler_soft.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_scrambler_soft_pydoc.h>

void bind_pdu_scrambler_soft(py::module& m)
{

    using pdu_scrambler_soft = ::gr::satellites::pdu_scrambler_soft;


    py::class_<pdu_scrambler_soft, gr::block, gr::basic_block, std::shared_ptr<pdu_scrambler_soft>>(
        m, "pdu_scrambler_soft", D(pdu_scrambler_soft))

        .def(py::init(&pdu_scrambler_soft::make), py::arg("sequence"), D(pdu_scrambler_soft, make))


        ;
}
